/**
 * Web Push (VAPID) for job alerts — no Firebase, no Google account.
 *
 * VAPID keys are self-generated by the operator (`npx web-push
 * generate-vapid-keys`) and pinned via VAPID_PUBLIC_KEY /
 * VAPID_PRIVATE_KEY. Without them, ephemeral keys are generated at boot
 * with a loud warning: subscriptions made against ephemeral keys die on
 * restart, which is fine for dev and wrong for production.
 *
 * Subscriptions are in-memory (the DB-free posture): a push endpoint URL
 * is device-addressing PII, so it is never persisted or published. Drivers
 * re-subscribe automatically whenever they go online. Payloads are
 * encrypted end-to-end to the device (RFC 8291) — the push relay
 * (Google/Mozilla/Apple) cannot read them.
 */

const webpush = require('web-push');

let publicKey = null;
let configured = false;

// pubkey (lowercase hex) → { subscription, areas, location, subscribedAt }
const subscriptions = new Map();

// Injectable transport so tests never hit a real push service
let transport = (subscription, payload) =>
    webpush.sendNotification(subscription, payload);

function init(env = process.env) {
    let priv = env.VAPID_PRIVATE_KEY;
    publicKey = env.VAPID_PUBLIC_KEY;
    if (!publicKey || !priv) {
        const generated = webpush.generateVAPIDKeys();
        publicKey = generated.publicKey;
        priv = generated.privateKey;
        console.warn('⚠️  VAPID_PUBLIC_KEY/VAPID_PRIVATE_KEY not set — generated ephemeral push keys.');
        console.warn('   Push subscriptions will not survive a restart. For production run');
        console.warn('   `npx web-push generate-vapid-keys` once and pin the keys in the environment.');
    }
    const subject = env.VAPID_SUBJECT || 'https://github.com/TheCryptoDonkey/DonkeyRide';
    webpush.setVapidDetails(subject, publicKey, priv);
    configured = true;
    return publicKey;
}

function getPublicKey() {
    return publicKey;
}

/** Minimal structural check on a browser PushSubscription.toJSON() */
function isValidSubscription(sub) {
    return !!(sub
        && typeof sub.endpoint === 'string'
        && /^https:\/\//.test(sub.endpoint)
        && sub.keys
        && typeof sub.keys.p256dh === 'string'
        && typeof sub.keys.auth === 'string');
}

function subscribe(pubkey, subscription, {
    areas = null, location = null, gender = null, womenOnly = false, role = 'provider',
    serviceOptions = null, domain = null
} = {}) {
    if (!pubkey || !isValidSubscription(subscription)) {
        return false;
    }
    subscriptions.set(pubkey.toLowerCase(), {
        subscription,
        // Riders subscribe too (matched / arrived / cancelled alerts) and
        // must never be swept up in job dispatch — hence the role.
        role: role === 'requester' ? 'requester' : 'provider',
        domain: typeof domain === 'string' && domain ? domain : null,
        areas: Array.isArray(areas) && areas.length > 0 ? areas : null,
        location: location || null,
        // Self-declared, for women-only matching of pushed jobs
        gender: gender || null,
        womenOnly: womenOnly === true,
        // Vehicle classes this driver can serve (null = default class only)
        serviceOptions: Array.isArray(serviceOptions) ? serviceOptions : null,
        subscribedAt: Date.now()
    });
    return true;
}

function unsubscribe(pubkey) {
    return subscriptions.delete((pubkey || '').toLowerCase());
}

/** Refresh dispatch targeting (working areas / last location / gender prefs) */
function updateTargeting(pubkey, { areas, location, gender, womenOnly, serviceOptions, domain } = {}) {
    const entry = subscriptions.get((pubkey || '').toLowerCase());
    if (!entry) {
        return;
    }
    if (Array.isArray(areas)) {
        entry.areas = areas.length > 0 ? areas : null;
    }
    if (location) {
        entry.location = location;
    }
    if (gender !== undefined) {
        entry.gender = gender || null;
    }
    if (womenOnly !== undefined) {
        entry.womenOnly = womenOnly === true;
    }
    if (Array.isArray(serviceOptions)) {
        entry.serviceOptions = serviceOptions;
    }
    if (typeof domain === 'string' && domain) {
        entry.domain = domain;
    }
}

function listSubscriptions() {
    return Array.from(subscriptions.entries())
        .map(([pubkey, entry]) => ({ pubkey, ...entry }));
}

/**
 * Send a payload to one subscribed driver. Expired subscriptions
 * (404/410 from the push service) are dropped so the map self-heals.
 * Never throws — push is always best-effort.
 */
async function sendTo(pubkey, payload) {
    const key = (pubkey || '').toLowerCase();
    const entry = subscriptions.get(key);
    if (!entry || !configured) {
        return false;
    }
    try {
        await transport(entry.subscription, JSON.stringify(payload));
        return true;
    } catch (error) {
        if (error.statusCode === 404 || error.statusCode === 410) {
            subscriptions.delete(key);
        } else {
            console.warn(`Push to ${key.slice(0, 8)}… failed:`, error.message);
        }
        return false;
    }
}

/** Test hook: replace the outbound transport */
function setTransport(fn) {
    transport = fn || ((subscription, payload) => webpush.sendNotification(subscription, payload));
}

/** Test hook: wipe state */
function reset() {
    subscriptions.clear();
}

module.exports = {
    init,
    getPublicKey,
    isValidSubscription,
    subscribe,
    unsubscribe,
    updateTargeting,
    listSubscriptions,
    sendTo,
    setTransport,
    reset
};
